### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by Alexander-Barth** [dressel/RTLSDR.jl#2]
I am wondering if you can make a release of your package. It would it make easier to share code that depend on RTLSDR.jl, for example a FM decoder in julia (https://nbviewer.jupyter.org/github/Alexander-Barth/APTDecoder.jl/blob/master/examples/FM%20radio.ipynb).

**Comment by dressel** [comment]
I'm definitely open to that. Give me a day or two figure out how to do it. I am glad you have found the package useful enough to warrant that.

**Comment by Alexander-Barth** [comment]
Great thanks! Let me know if you have any questions. Personally I find the GitHub app quite useful https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app .

**Comment by dressel** [comment]
Hey, sorry for the delay. I'm just trying to clean it up a bit (fixing a couple bugs, improving docs). 

I'm thinking of removing the PyPlot dependency. I think it will make the package load a lot quicker. Would you be ok with that removal, or are you using it somewhere?

I've also noticed that you call the c_interface functions directly instead of the more high-level Julia functions (in RTLSDR.jl). Is there a reason for that (beyond that the documentation is horrible)? I've added some of the functions you use (set_agc_mode, set_tuner_gain_mode). I'd like it if the user didn't have to muck around with the pointers themselves, letting the RtlSdr type take care of it. What are your thoughts on that? What would have to change to make that viable?

**Comment by Alexander-Barth** [comment]
yes, removing the PyPlot dependency is a good idea.

There is no particular reason why I used the low-level functions and I agree it would be better and safer to use the higher-level functions who check if the pointer is still valid. I will update my code accordingly.

**Comment by dressel** [comment]
Ok cool, I used the GitHub app like you suggested. I suppose now we just wait for them to merge the pull request.

Feel free to look over recent changes and make comments. If you'd like to link to your notebooks and examples in the README, I'd be ok with that.

**Comment by Alexander-Barth** [comment]
Great! Thanks a lot! I think I will need to clean-up the notebook a bit more and then it would indeed be nice to link it.
